export default {
  index: 0,
  title: "",
  company: "",
  salaryMin: 0,
  salaryMax: 0,
  description: "",
  experienceLevel: "Senior",
  tech: [],
  applied: false,
  interviewCount: 0,
  easyApply: false,
  requiresPreInterviewTest: false,
  requiresHomework: false,
};
